### ISSUE TITLE
license of project?

### ISSUE THREAD

**Issue by top-on** [ColeMurray/medium-show-and-tell-caption-generator#2]
Hi, thanks for sharing this great showcase!
What licence does apply to your work?
I am seeing an Apache License for caption_generator.py.
Is your intention to share the entire repository under this license?

**Comment by ColeMurray** [comment]
Hello @ThorbenJensen,

I have added an MIT license available at https://github.com/ColeMurray/medium-show-and-tell-caption-generator/blob/master/LICENSE

Thank you,

Cole Murray

**Comment by top-on** [comment]
@ColeMurray 
thanks for the update! I will add an open license to my fork, too.
