### ISSUE TITLE
Access to original checkpoint

### ISSUE THREAD

**Issue by thunfischtoast** [ColeMurray/medium-show-and-tell-caption-generator#5]
Hi Cole,

I followed your tutorial and had some great results with it! I'd now like to fine-tune the exiting model further, however I could not manage to continue training using the frozen graph (show-and-tell.pb). Would it be possible to point us towards the original checkpoint and graph.pbtxt files? The help would be well appreciated.

Thank you very much
Christian

**Comment by ColeMurray** [comment]
@thunfischtoast,

I do not have my checkpoints available. I did find a repository that contains a set of pre-trained checkpoints you can use.

https://github.com/KranthiGV/Pretrained-Show-and-Tell-model

You can find Google's repository on im2txt here: https://github.com/tensorflow/models/tree/master/research/im2txt

Thank you,

Cole Murray
